services:
  nestjs-observability-stack:
    build: .
    container_name: nestjs-observability-stack
    ports:
      - "3000:3000"
    depends_on:
      - metr101-prometheus

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.2.2
    container_name: grafana
    ports:
      - "3030:3000"
