scrape_configs:
  - job_name: nestjs-observability-stack-service
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["nestjs-observability-stack:3000"]